option(BUILD_TESTING            "build unit tests"          OFF)
option(BUILD_SHARED_LIBS        "build shared libraries"    OFF)

set(CMAKE_DEBUG_POSTFIX "d")
set(CMAKE_STATIC_LIBRARY_SUFFIX ".static${CMAKE_STATIC_LIBRARY_SUFFIX}")

set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")

if (${CMAKE_SIZEOF_VOID_P} STREQUAL "4")
	set(CMAKE_SHARED_LIBRARY_SUFFIX "-x86${CMAKE_SHARED_LIBRARY_SUFFIX}")
	set(CMAKE_STATIC_LIBRARY_SUFFIX "-x86${CMAKE_STATIC_LIBRARY_SUFFIX}")
else()
	set(CMAKE_SHARED_LIBRARY_SUFFIX "-x64${CMAKE_SHARED_LIBRARY_SUFFIX}")
	set(CMAKE_STATIC_LIBRARY_SUFFIX "-x64${CMAKE_STATIC_LIBRARY_SUFFIX}")
endif()

